data:
  input_path: "data/raw/global_electricity_production_data.csv"
  output_path: "data/processed/electricity_clean_2023.csv"

processing:
  latest_year: 2023
  use_log_scaling: true

thresholds:
  variance: 0.01
  correlation: 0.9

